"""empty message

Revision ID: 41bc23e0a0ba
Revises: f5ef45eeef86
Create Date: 2024-04-03 17:02:39.851037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41bc23e0a0ba'
down_revision = 'f5ef45eeef86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('foreignkey', 'unit', ['unit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('foreignkey', type_='foreignkey')
        batch_op.drop_column('unit_id')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
