"""empty message

Revision ID: b945e5639441
Revises: 41bc23e0a0ba
Create Date: 2024-04-03 18:05:37.633692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b945e5639441'
down_revision = '41bc23e0a0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicleallocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loosing_unit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('foreignkey', 'unit', ['loosing_unit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicleallocation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('loosing_unit_id')

    # ### end Alembic commands ###
