"""empty message

Revision ID: cc8b2f02718d
Revises: 79e5ba1280bd
Create Date: 2024-04-04 01:21:17.127110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8b2f02718d'
down_revision = '79e5ba1280bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiclelog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiclelog', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
